config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/links' => "links#index", as: :links
  post '/links' => "links#create"
  get '/links/new' => "links#new", as: :new_link
  get '/links/:admin_code/edit' => "links#edit", as: :edit_link
  put '/links/:admin_code' => "links#update", as: :expire_link
  patch '/links/:admin_code' => "links#update"
  delete '/links/:admin_code' => "links#destroy", as: :destroy_link

  get '/logout' => "auths#logout" # above shortcode so it takes precedence because they look the same
  mount Sidekiq::Web => '/sidekiq'
  get '/:short_code' => "links#visit"
  get '/admin/:admin_code' => "links#show", as: :link

  root to: "links#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  MAX_RETRIES = 10 # eventually this will choke when we have lots of links but it's going to be awhile

  before_validation :verify_or_add_codes

  validates(:destination, presence: true)
  validates(:short_code, presence: true)
  validates(:admin_code, presence: true)

  scope :active, -> { where(expired_at: nil) }

  def verify_or_add_codes
    codes = [:short_code, :admin_code]
    codes.each do |code|
      next if self[code].present?
      MAX_RETRIES.times do # this is for handling collisions
        new_code = self.class.generate_code
        break self[code] = new_code if self.class.where("#{code} = ?", new_code).empty?
      end
    end
  end

  def self.generate_code
    SecureRandom.hex(3) # generates a 6 digit hex code, 16^6 = 16,777,216 possible tokens
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # this is poorly done but you didn't want users; I'm just showing you I know where this goes
  # If I wanted this terrible thing in production I would put that password in an environment variable so that it wasn't
  # available in github, but since I actually want you to be able to see it, here it is.
  # this should be sending a jwt token to a service which decodes it and authorizes
  # I used :password because it's automatically filtered in the logs (/config/initializers/filter_parameter_logging.rb)
  def authenticate(password=params[:password])
    if (password == "12180 Millennium" || session[:authenticated] == true)
      session[:authenticated] = true
      return
    end
    false
  end

  def clear_authentication
    session.delete :authenticated
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  # GET /logout
  # GET /logout.json
  def logout
    clear_authentication
    redirect_to new_link_url
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate, only: [:index, :destroy]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    redirect_to new_link_url and return unless (session[:authenticated] == true)
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
    redirect_to new_link_url unless @link.present?
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_path(admin_code: @link.admin_code), notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    modified_params = link_params.to_h.symbolize_keys
    modified_params[:expired_at] = Time.zone.now if (link_params[:expired_at] == "true")

    respond_to do |format|
      if @link.update(modified_params)
        format.html { redirect_to link_path, admin_code: @link.admin_code, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    redirect_to new_link_url and return unless (session[:authenticated] == true)
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /fedcba
  # GET /fedcba.json
  def visit
    @link = Link.active.find_by_short_code(params[:short_code])
    if @link.present?
      HitWorker.perform_async(@link.id, Time.zone.now, request.user_agent)
      redirect_to @link.destination, status: :moved_permanently and return
    end
    raise ActionController::RoutingError.new('Not Found')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find_by_admin_code(params[:admin_code])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:destination, :short_code, :admin_code, :use_count, :expired_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logout_button
    if session[:authenticated] == true
      " | ".concat(link_to('Logout', 'logout')).html_safe
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def expired_at
    if @link.id.nil?
      return
    elsif @link.expired_at.nil?
      render 'links/expire_button'
    else
      render 'links/expire_info'
    end
  end

  def analytics_value(method, default_return="N/A")
    sorted_values = @link.public_send(method).sort_by {|_key, value| value}.to_h
    return default_return unless sorted_values.present?
    case method
    when :day_of_week
      Date::DAYNAMES[sorted_values.first[0].to_i]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortscreen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Shortscreen</h1>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/links/_expire_button.html.erb
<%= form_with(url: expire_link_path, method: :patch, local: true, model: @link) do |form| %>
  <%= form.hidden_field :expired_at, value: true %>
  <div class="actions">
    <%= form.submit "Expire Link" %>
  </div>
<% end %>

app/views/links/_expire_info.html.erb
<p>
  <strong>Expired at:</strong>
  <%= @link.expired_at %>
</p>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :short_code %>
    <%#= form.text_field :short_code %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :admin_code %>
    <%#= form.text_field :admin_code %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :use_count %>
    <%#= form.number_field :use_count %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :expired_at %>
    <%#= form.datetime_select :expired_at %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= expired_at %>

app/views/links/edit.html.erb
<%= link_to 'Show', @link %> |
<%= link_to 'New', new_link_path %>
<h2>Editing Link <%= @link.id %></h2>

<%= render 'form', link: @link %>

app/views/links/index.html.erb
<%= link_to 'New Link', new_link_path %><%= logout_button %>

<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Short code</th>
      <th>Admin code</th>
      <th>Use count</th>
      <th>Expired at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.destination %></td>
        <td><%= link.short_code %></td>
        <td><%= link.admin_code %></td>
        <td><%= link.use_count %></td>
        <td><%= link.expired_at %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/links/new.html.erb
<h2>New Link</h2>

<%= render 'form', link: @link %>

app/views/links/show.html.erb
<!--<%#= link_to 'Edit', edit_link_path(@link[:admin_code]) %> |-->
<%= link_to 'New', new_link_path %>

<h2>Link <%= @link.short_code %></h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Destination:</strong>
  <%= link_to @link.destination, @link.destination %>
</p>

<p>
  <strong>Short link:</strong>
  <% short_link = root_url.concat(@link.short_code) %>
  <%= link_to short_link, short_link %>
</p>

<p>
  <strong>Admin link:</strong>
  <% admin_link = root_url.concat('admin/', @link.admin_code) %>
  <%= link_to admin_link, admin_link %>
</p>

<p>
  <strong>Use count:</strong>
  <%= @link.use_count %>
</p>

<p>
  <strong>Most popular day of week:</strong>
  <%= analytics_value(:day_of_week) %>
</p>

<p>
  <strong>Most popular hour of day (24-hour clock):</strong>
  <%= analytics_value(:hour_of_day) %>
</p>

<p>
  <strong>User agents ([count]: [user agent])</strong><br>
  <% @link.user_agents.sort_by {|_key, value| value}.each do |ua, count| %>
    <%= count.to_s + ': ' + ua %>
  <% end %>
</p>

<%= expired_at %>